[project]
name = "default"
master = "master"
common_modules = ["core", "tm", "fwt", "exc", "clk", "nav", "pvu", "grp"]
mcc_id = 0
module_dirs = [
  "modules/photon/core",
  "modules/photon/tm",
  "modules/photon/fwt",
  "modules/photon/test",
  "modules/photon/exc",
  "modules/photon/clk",
  "modules/photon/nav",
  "modules/photon/pvu",
  "modules/photon/fl",
  "modules/photon/grp",
]

[[devices]]
name = "master"
id = 1
cmd_targets = ["slave1", "master"]
tm_sources = ["slave1", "master"]
modules = ["test", "fl"]

[[devices]]
name = "slave1"
tm_sources = ["master"]
cmd_targets = ["slave1"]
id = 2

