[project]
name = "default"
master = "model1"
common_modules = ["core", "tm", "int", "fwt", "exc", "clk", "nav"]
mcc_id = 0
module_dirs = [
  "modules/photon/core",
  "modules/photon/tm",
  "modules/photon/fwt",
  "modules/photon/int",
  "modules/photon/test",
  "modules/photon/exc",
  "modules/photon/clk",
  "modules/photon/nav",
  "modules/photon/pvu",
  "modules/photon/fl",
]

[[devices]]
name = "model1"
id = 1
cmd_targets = ["model2"]
tm_sources = ["model2"]
modules = ["pvu", "test", "fl"]

[[devices]]
name = "model2"
id = 2

