[project]
name = "default"
master = "model1"
common_modules = ["core", "tm", "fwt", "exc", "clk", "nav", "pvu"]
mcc_id = 0
module_dirs = [
  "modules/photon/core",
  "modules/photon/tm",
  "modules/photon/fwt",
  "modules/photon/test",
  "modules/photon/exc",
  "modules/photon/clk",
  "modules/photon/nav",
  "modules/photon/pvu",
  "modules/photon/fl",
  "modules/photon/grp",
]

[[devices]]
name = "model1"
id = 1
cmd_targets = ["model2"]
tm_sources = ["model2"]
modules = ["test", "fl", "grp"]

[[devices]]
name = "model2"
id = 2

