[project]
name = "default"
master = "model1"
common_modules = ["core", "tm", "int", "fwt", "exc"]
mcc_id = 0
module_dirs = [
  "modules/photon/core",
  "modules/photon/tm",
  "modules/photon/fwt",
  "modules/photon/int",
  "modules/photon/test",
  "modules/photon/exc"
]

[[devices]]
name = "model1"
id = 1
modules = ["test"]
cmd_targets = ["model2"]
tm_sources = ["model2"]

[[devices]]
name = "model2"
id = 2
